### PR TITLE
Merging the D fmod to Master

### LINKED ISSUE #8: cellTracker
The package cellTracker is used by the following lines in `cellTracker_core.R`, but the package cellTracker is not listed under **Imports** in DESCRIPTION. This causes the build to fail.

    ## %dopar%
    all_results <-
      tryCatch(foreach::foreach(j = (1:nrow(all_params)),
                                .verbose = TRUE,
                                .packages = "cellTracker") %dopar% {

                                  # Verbose
                                  message(".", appendLF = FALSE)

                                  #visualize_img(tmp_img)
                                  b <- bpass(image_array = tmp_img,
                                             lnoise = all_params$lnoise[j],
                                             lobject = all_params$diameter[j],
                                             threshold = all_params$threshold[j])
                                  tmpOUT <- list(img = b)

                                  tryCatch({
                                    pk <- suppressMessages(
                                      pkfnd(im = b,
                                            th = all_params$threshold[j],
                                            sz = next_odd(all_params$diameter[j])))

                                    cnt <- suppressMessages(
                                      cntrd(im = b, mx = pk,
                                            sz = next_odd(all_params$diameter[j])))

                                    tmpOUT[["count"]] <- nrow(cnt)

                                  }, error = function(e) {
                                    tmpOUT[["count"]] <- 0

                                  })
                                  tmpOUT
                                }, error = (function(e) {
                                  print(e)
                                  try(parallel::stopCluster(cl), silent = TRUE)
                                  return(NULL)
                                }))
    message("Done!", appendLF = TRUE)
    try({suppressWarnings(parallel::stopCluster(cl))}, silent = TRUE)
  }

### PR DESCRIPTION
**Pull request by SystemsBiologist**
Removing dependencies, recreating datasets.

### CODE REVIEW

**Comment by wleoncio** [comment]
I'm fine with everything, but I don't understand why the following files were deleted:

- .Rbuildignore
- .gitignore
- .travis.yml
- CellMigRationLogo.png
- DESCRIPTION
- LICENSE.md

@dami82, it OK someone adds these files back as a commit to the DFmod branch before merging?

**Review by wleoncio — CHANGES_REQUESTED** [review]
Please re-add or justify the removal of the following files:
 
-     .Rbuildignore
-     .gitignore
-     .travis.yml
-     CellMigRationLogo.png
-     DESCRIPTION
-     LICENSE.md

**Comment by dami82** [comment]
Hello,

Did you get my previous email? Please, don’t take this the wring way. Briefly, I removed ALL files (no exception), rebuilt the skeleton from scratch, and then the package. As I wrote before, you should feel free to add the files I left out.
As you know, DESCRIPTION is crucial, so please modify on the top of my version rather than rolling back to the one in master.

Best regards,
Damiano

——
Damiano Fantini

**Comment by wleoncio** [comment]
I have added the missing files and updated the documentation. A local check on my computer shows everything is fine:
bilde

Let's see if the Travis check also passes (it pointed to a different error, but error reports can be misleading). If it does, we're good to go.

**Review by wleoncio — APPROVED** [review]

**Pull request merged**
