### PR TITLE
vapply and seq_len fixes in LinearConv2

### PR DESCRIPTION
**Pull request by osorensen**

### CODE REVIEW

**Comment by osorensen** [comment]
I will follow good practice and make many small commits. Then you can test that each piece works as it should. Will replace `1:N` with `seq_len(N)` whenever it co-occurs with `sapply`.

**Review by wleoncio — APPROVED** [review]
Coding looks proper. Unit tests to be added when addressing issue #36.

**Comment by wleoncio** [comment]
Thank you for your contribution, @osorensen. For future reference, please open a PR (or merge directly) to the `develop` branch. We'll eventually merge that to master for resubmission.

**Comment by osorensen** [comment]
Ok, thanks @wleoncio . Create a bunch of new PRs before I saw your message, but will open them to the develop branch hereafter.

**Pull request merged**
